#!/bin/bash
if [[ $1 == "clean" ]]; then
    gradle clean
fi
export GRADLE_COMPILE_ONLY=true
gradle shadowJar
if [[ $? == 0 ]]; then
    gulp
    if [[ $? != 0 ]]; then
        echo "************************ COMPILE FAILED ****************************"
    fi
else
    echo "************************ COMPILE FAILED ****************************"
    exit
fi
